spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_erhuo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      password: 123456
      username: root
#??????????

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.usst.programer.entity
  mapper-locations: classpath:mapper/*.xml


server:
  servlet:
    encoding:
      enabled: false
    context-path: /erhuo

#???????
  port: 80