spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_erhuo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      password: root
      username: root
#??????????

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.usst.programer.entity
  mapper-locations: classpath:mapper/*.xml


server:
  servlet:
    encoding:
      enabled: false


#???????
  port: 80

#存图片的路径
img-path:
  #填电脑上当前项目的文件夹
  local: D:/code/erhuo/src/main/resources/static/img/
  #填电脑上当前项目的target对应的文件夹)
  target: D:/code/erhuo/target/classes/static/img/
  #从网页上访问服务器的路径，不需要动
  server: ./img/